load(":color.bzl", "color")

package(default_visibility=["//visibility:public"])

label_flag(name="color", build_setting_default=":white")

color(name="white")
color(name="black")
color(name="gray")

